In [1]:
import numpy as np

1. Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.

In [2]:
x = np.arange(11)
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10]


2. Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.

In [3]:
x = np.zeros((3, 3))
print(x)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


3. Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.

In [4]:
x = np.random.randint(1, 11, size=(5, 5))
print(x)

[[ 7  3  3  4  4]
 [ 2  6  5  5  6]
 [10  4  3  2  6]
 [ 6  6  8  2  1]
 [ 8  8  2  5  9]]


4. Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.

In [5]:
x = np.random.randint(2, size=(4, 4))
print(x)

[[0 1 0 1]
 [0 1 1 1]
 [0 1 0 1]
 [0 1 0 1]]


5. Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.

In [6]:
x = np.random.randint(1, 11, size=5)
y = np.random.randint(1, 11, size=5)
print(x + y)
print(x - y)
print(x * y)

[15 12 14  7 17]
[ 5  6  2  5 -3]
[50 27 48  6 70]


6. Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.

In [7]:
x = np.random.randint(1, 11, size=7)
y = np.random.randint(1, 11, size=7)
print(np.dot(x, y))

208


7. Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.

In [8]:
x = np.random.randint(1, 11, size=(2, 2))
y = np.random.randint(1, 11, size=(2, 3))
print(np.dot(x, y))

[[ 52  60  42]
 [100 120  60]]


8. Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.

In [9]:
x = np.random.randint(1, 11, size=(3, 3))
print(np.linalg.inv(x))

[[ 0.02857143 -0.31428571  0.65714286]
 [-0.28571429  0.14285714  0.42857143]
 [ 0.34285714  0.22857143 -1.11428571]]


9. Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.

In [10]:
x = np.random.randint(2, size=(4, 4))
print(x.T)

[[0 1 0 1]
 [1 0 0 0]
 [1 0 1 0]
 [0 0 0 0]]


10. Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор.

In [11]:
x = np.random.randint(1, 11, size=(3, 4))
y = np.random.randint(1, 11, size=4)
print(np.dot(x, y))

[96 69 94]


11. Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор.

In [12]:
x = np.random.randint(2, size=(2, 3))
y = np.random.randint(2, size=3)
print(np.dot(x, y))

[0 0]


12. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення.

In [13]:
x = np.random.randint(1, 11, size=(2, 2))
y = np.random.randint(1, 11, size=(2, 2))
print(x * y)

[[ 3 16]
 [48 60]]


13. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.

In [14]:
x = np.random.randint(1, 11, size=(2, 2))
y = np.random.randint(1, 11, size=(2, 2))
print(np.dot(x, y))

[[ 98  59]
 [106  55]]


14. Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці.

In [15]:
x = np.random.randint(1, 101, size=(5, 5))
print(x.sum())               

1326


15. Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.

In [16]:
x = np.random.randint(1, 11, size=(4, 4))
y = np.random.randint(1, 11, size=(4, 4))
print(x - y)

[[ 3  3  0 -3]
 [-1  2 -2  0]
 [ 0  6 -5  8]
 [-2 -4  1  0]]


16. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.

In [17]:
x = np.random.randint(2, size=(3, 3))
print(x.sum(axis=1))

[1 1 3]


17. Створіть матрицю розміром 3x4 з довільними цілими числами і створінь матрицю з квадратами цих чисел.

In [18]:
x = np.random.randint(1, 11, size=(3, 4))
print(np.square(x))

[[  4  36  64 100]
 [  9   4   4   4]
 [ 36  49 100  64]]


18. Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел.

In [19]:
x = np.random.randint(1, 51, size=4)
print(np.sqrt(x))

[7.         2.         5.56776436 6.164414  ]
